apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name keda
spec:
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: *name
      targetRevision: 2.17.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
