apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-cd
spec:
  parentRefs:
    - name: trial-studio-gateway
      namespace: cilium
  hostnames: ["argo-cd.trial.studio"]
  rules:
    - backendRefs:
        - name: argo-cd-argocd-server
          port: 443